workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-s3-cache

pipeline:
  test:
    image: golang:1.9
    group: testing
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out

  build:
    image: golang:1.9
    group: testing
    commands: sh .drone.sh

  publish_linux_amd64:
    image: plugins/docker
    group: tags
    repo: plugins/s3-cache
    tags: [ "latest", "1.1", "1" ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish_linux_armhf:
    image: plugins/docker
    group: tags
    repo: plugins/s3-cache
    tags: [ "linux-arm" ]
    dockerfile: Dockerfile.armhf
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish_linux_aarch64:
    image: plugins/docker
    group: tags
    repo: plugins/s3-cache
    tags: [ "linux-arm64" ]
    dockerfile: Dockerfile.aarch64
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
